version: "3.6"

services:
  influxdb:
    image: "influxdb:1.8"
    restart: "always"
    ports:
    - "8086:8086"
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "eventlog"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"

  grafana:
    # Necessary to get around `database` datasource provisioning bug
    # See: https://github.com/grafana/grafana/issues/64795
    image: "grafana/grafana-oss-dev:9.5.0-107958pre"
    restart: "always"
    ports:
    - "3000:3000"
    volumes:
    - "./grafana/datasources:/etc/grafana/provisioning/datasources"
    - "./grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
    - "./grafana/dashboards:/var/lib/grafana/dashboards"
    - "grafana-storage:/var/lib/grafana"

volumes:
  grafana-storage:
